### ISSUE TITLE
"/check" endpoint renamed to "/authorize"

### ISSUE THREAD

**Issue by PrasadJayakumar** [warrant-dev/warrant-node#54]
I happened to download and build from source

https://github.com/warrant-dev/warrant  [main]

Based on the latest build, looks like /check is changed /authorize.  I am not sure. But demo code "hasPermission" worked only after this change

https://docs.warrant.dev/quickstart/role-based-access-control/

node_modules\@warrantdev\warrant-node\dist\modules\Authorization.js

`static makeCheckRequest(check, options = {}) {
        return __awaiter(this, void 0, void 0, function* () {
            const response = yield WarrantClient_1.default.httpClient.post({
                url: '/${constants_1.API_VERSION}/authorize',
                data: check,
                options,
            });
            return response.code === 200;
        });
}`

**Comment by kkajla12** [comment]
@PrasadJayakumar, can you try again with the latest release of warrant ([v1.3.0]())?

**Comment by PrasadJayakumar** [comment]
Working without making any changes to the endpoints in JS client library.  I have downloaded the binary and tried this time.  

Thank you for your prompt response.
